---
name: Style and load

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run editorconfig-checker
        run: editorconfig-checker

      - name: Load prompt
        run: |
          sudo apt-get install -y zsh
          zsh -f -c 'source git-prompt.zsh; print -P $(_zsh_git_prompt_git_status)'
